title: new-language.guide
description: >
  How do I start a project in a new language?
baseurl: ""
url: "https://new-language.guide"

google_analytics: UA-101858487-1

port: 8080
host: 0.0.0.0
show_dir_listing: false

markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - contributing.md
  - Gemfile
  - Gemfile.lock
  - template.md

permalink: pretty

collections:
  guides:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: page
  - scope:
      path: "_guides/ruby"
    values:
      languages:
        - Ruby
        - object-oriented
        - dynamically-typed
  - scope:
      path: "_guides/node"
    values:
      languages:
        - JavaScript
        - object-oriented
        - dynamically-typed

